artgallery/Controllers/AuctionGalleryController.cs
using artgallery.Models;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace artgallery.Controllers
{
    public class AuctionGalleryController : Controller
    {

        OnlineArtGalleryEntities2 db = new OnlineArtGalleryEntities2();
        // GET: AuctionGallery
        public ActionResult Index()
        {
            List<AucCategory> getCategry = db.AucCategories.ToList();
            SelectList categoryList = new SelectList(getCategry, "cat_Id", "cat_name");
            
            ViewBag.categorylist = categoryList.ToList();

            return View(db.AuctionGalleries.ToList());
        }

        //get: AuctionGallery/Upload
        [Authorize]
        public ActionResult Upload()
        {

            if (Session["UserProfile"] == null)
            {
                return RedirectToAction("MemberLogin", "Customer");

            }
            var getAdmins = db.Adminboxes.ToList();
            SelectList adminList = new SelectList(getAdmins, "adminId", "adminFirstName");
            ViewBag.getAdminList = adminList;

            var getArtist = db.Members.ToList();
            SelectList artistList = new SelectList(getArtist, "memberId", "memberFirstName");
            ViewBag.getArtistList = artistList;
            return View();
        }
        [HttpPost]
        public ActionResult Upload(AuctionGallery pics, HttpPostedFileBase imgfile)
        
        {




                string path = uploadimage(imgfile);

                if (path.Equals("-1"))
                {
                    ViewBag.error = "image could not be uploaded";

                }
                else
                {
                    AuctionGallery gal = new AuctionGallery();
                    gal.AucTitle = pics.AucTitle;
                    gal.AucDescription = pics.AucDescription;
                    gal.Currentbid = pics.Currentbid;
                    gal.AucCategory = pics.AucCategory;
                    gal.AucPic = path;//ssasa
                    gal.IsSold = false;
                    gal.EndingDate = pics.EndingDate;
                    
                    gal.DateUploaded = pics.DateUploaded;    //DateTime.Now;
                    gal.ArtistId_FK = Convert.ToInt32(Session["UserId"].ToString());  //sessionid

                    db.AuctionGalleries.Add(gal);
                    db.SaveChanges();

                    Response.Redirect("Index");
                }



                /*if (ModelState.IsValid)
                {
                    db.AuctionGalleries.Add(pics);
                    if (db.SaveChanges() > 0)
                    {
                        TempData["msg"] = "Pic Uploaded";
                        return RedirectToAction("Index");
                    }
                    else
                    {
                        return View();
                    }
                }*/
                return View();
        }
        public ActionResult Checkout()
        {
            return View();
        }





        public ActionResult CheckoutAuc() //create of AucInvice
        {
            return View();
        }

        [HttpPost]
        public ActionResult CheckoutAuc(AuctionInvoice invc) //create of AucInvice
        {
            if (ModelState.IsValid)
            {
                db.AuctionInvoices.Add(invc);                                             // (Modelvar).().Add(value entered in parameters)

                if ((db.SaveChanges()) > 0) // 
                {
                    TempData["msg"] = "Invoice Updated";
                    return RedirectToAction("CustomersIndex");
                }
                else
                {
                    return View();
                }
            }
            return View();
        }


        public string uploadimage(HttpPostedFileBase file)

        {

            Random r = new Random();

            string path = "-1";

            int random = r.Next();

            if (file != null && file.ContentLength > 0)

            {

                string extension = Path.GetExtension(file.FileName);

                if (extension.ToLower().Equals(".jpg") || extension.ToLower().Equals(".jpeg") || extension.ToLower().Equals(".png"))

                {
                    try

                    {



                        path = Path.Combine(Server.MapPath("~/Content/upload"), random + Path.GetFileName(file.FileName));

                        file.SaveAs(path);

                        path = "~/Content/upload/" + random + Path.GetFileName(file.FileName);



                        //    ViewBag.Message = "File uploaded successfully";

                    }

                    catch (Exception)

                    {

                        path = "-1";

                    }

                }

                else

                {

                    Response.Write("<script>alert('Only jpg ,jpeg or png formats are acceptable....'); </script>");

                }

            }



            else

            {

                Response.Write("<script>alert('Please select a file'); </script>");

                path = "-1";

            }







            return path;


        }




    }
}

artgallery/Controllers/CustomerController.cs
    using artgallery.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data.Entity;
using System.Net;
using System.Web.Security;

namespace artgallery.Controllers
{
    public class CustomerController : Controller
    {

        OnlineArtGalleryEntities2 db = new OnlineArtGalleryEntities2();
        // GET: Customer
        public ActionResult Index()
        {
            return View();
        }

       

        public ActionResult Register() // create page
        {
            /*var getAdmins = db.Adminboxes.ToList();
            SelectList adminList = new SelectList(getAdmins, "adminId", "adminFirstName");
            ViewBag.getAdminList = adminList;*/
            return View();
        }

        [HttpPost]
        public ActionResult Register(Member memberadd)
        {

            if (ModelState.IsValid)
            {
                db.Members.Add(memberadd);

                

                if (db.SaveChanges()>0)
                {
                    TempData["msg"] = "Account Created \n SignIn to Continue";
                    return RedirectToAction("MemberLogin");
                }
                else
                {
                    return View();
                }
            }
            else
            {
                return View();
            }

            
        }

        [HttpGet]
        public ActionResult MemberLogin() // login authenticatin 2
        {
            return View();
        }

        [HttpPost]
        public ActionResult MemberLogin(Member m) // login authenticatin 2
        {

            Member membes = db.Members.Where(x => x.memberEmail == m.memberEmail && x.memberPassword == m.memberPassword).FirstOrDefault();


            if (membes != null)
            {
                FormsAuthentication.SetAuthCookie(m.memberEmail, false);
                var profileData = new Member
                {
                    memberId = m.memberId,
                    memberFirstName = m.memberFirstName
                };

                this.Session["UserProfile"] = profileData;
                Session["UserId"] = m.memberId;
                Session["UName"] = m.memberFirstName + m.memberLastName;
                return RedirectToAction("Account");
            }
            else
            {
                ViewBag.error = "Invalid Username or id";
            }

            return View();
        }


        [Authorize]
        public ActionResult Account()  // profile ViewRead Page
        {

            if (Session["UserProfile"] == null)
            {
                return RedirectToAction("MemberLogin");
            }

            return View();
        }

        public ActionResult Logout()
        {
            Session.RemoveAll();
            Session.Abandon();

            return RedirectToAction("MemberLogin");
        }
    }
}

artgallery/Controllers/SimpleArtGalleryController.cs
using artgallery.Models;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;


namespace artgallery.Controllers
{
    public class SimpleArtGalleryController : Controller
    {
        OnlineArtGalleryEntities2 db = new OnlineArtGalleryEntities2();
        // GET: SimpleArtGallery
        public ActionResult Index()
        {
            List<ArtCategory> getCategry = db.ArtCategories.ToList();
            SelectList categoryList = new SelectList(getCategry, "cat_Id", "cat_name");
            ViewBag.categorylist = categoryList;



            return View(db.ArtGalleries.ToList());
        }


        //get: SimpleArtGallery/Upload
        [Authorize]
        [HttpGet]
        public ActionResult Upload()
        {


            if (Session["UserProfile"] == null)
            {
                return RedirectToAction("MemberLogin", "Customer");

            }
            else {

                List<ArtCategory> getCategry = db.ArtCategories.ToList();
                SelectList categoryList = new SelectList(getCategry, "cat_Id", "cat_name");
                ViewBag.categorylist = categoryList;

                var getAdmins = db.Adminboxes.ToList();
            SelectList adminList = new SelectList(getAdmins, "adminId", "adminFirstName");
            ViewBag.getAdminList = adminList;

            var getArtist = db.Members.ToList();
            SelectList artistList = new SelectList(getArtist, "memberId", "memberFirstName");
            ViewBag.getArtistList = artistList;

            return View();
            }
        }
        [Authorize]
        [HttpPost]
        public ActionResult Upload(HttpPostedFileBase imgfile, ArtGallery pics)
        {
            /*
                        string filename = Path.GetFileName(file.FileName);
                        string _filename = DateTime.Now.ToString("yymmssff") + filename;

                        string path = Path.Combine(Server.MapPath("~/Content/Data"), _filename);

                        pics.ArtPic = "~/Content/Data" + _filename;

                        db.ArtGalleries.Add(pics);

                        if (db.SaveChanges()>0)
                        {
                            file.SaveAs(path);
                            ViewBag.msg = "Picture Added to GAllery";
                            ModelState.Clear();
                        }
            */


            string path = Uploadimage(imgfile);



            if (path.Equals("-1"))
            {
                ViewBag.error = "image could not be uploaded";

            }
            else
            {
                ArtGallery gal = new ArtGallery();
                gal.ArtTitle = pics.ArtTitle;
                gal.ArtDescription = pics.ArtDescription;
                gal.ArtPrice = pics.ArtPrice;
                gal.ArtCategory = pics.ArtCategory;
                gal.ArtPic = path;//ssasa
                gal.IsSold = false;
                gal.approvalDate = pics.approvalDate;    //DateTime.Now;
                gal.artistId_FK = Convert.ToInt32(Session["UserId"].ToString());  //sessionid

                db.ArtGalleries.Add(gal);
                db.SaveChanges();

                ViewBag.msg = "Pic Uploaded Sucessfully";


                Response.Redirect("Index");
            }

            /*if (ModelState.IsValid)
            {
                db.ArtGalleries.Add(pics);
                if (db.SaveChanges() > 0)
                {
                    TempData["msg"] = "Pic Uploaded";
                    return RedirectToAction("Index");
                }
                else
                {
                    return View();
                }
            }*/
            return RedirectToAction("Upload");
        }

        public ActionResult CheckoutArt() //create of ArtInvice
        {
            return View();
        }

        [HttpPost]
        public ActionResult CheckoutArt(ArtInvoice invc) //create of AucInvice
        {
            if (ModelState.IsValid)
            {
                db.ArtInvoices.Add(invc);                                             // (Modelvar).().Add(value entered in parameters)

                if ((db.SaveChanges()) > 0) // 
                {
                    TempData["msg"] = "Invoice Updated";
                    return RedirectToAction("CustomersIndex");
                }
                else
                {
                    return View();
                }
            }
            return View();
        }


        public string Uploadimage(HttpPostedFileBase imgfile)

        {
            
            Random r = new Random();

            string path = "-1";

            int random = r.Next();

            if (imgfile != null && imgfile.ContentLength > 0)

            {

                string extension = Path.GetExtension(imgfile.FileName);

                if (extension.ToLower().Equals(".jpg") || extension.ToLower().Equals(".jpeg") || extension.ToLower().Equals(".png"))

                {
                    try

                    {



                        path = Path.Combine(Server.MapPath("~/Content/Data/"), random + Path.GetFileName(imgfile.FileName));

                        imgfile.SaveAs(path);

                        path = "~/Content/Data/" + random + Path.GetFileName(imgfile.FileName);



                        //    ViewBag.Message = "File uploaded successfully";

                    }

                    catch (Exception ex)

                    {
                        ViewBag.error2 = ex;/// nothing just removing error
                        path = "-1";

                    }

                }

                else

                {

                    Response.Write("<script>alert('Only jpg ,jpeg or png formats are acceptable....'); </script>");

                }

            }



            else

            {

                Response.Write("<script>alert('Please select a file'); </script>");

                path = "-1";

            }







            return path;


        }


    }
}

artgallery/Views/Customer/Account.cshtml
@model artgallery.Models.Member
@{
    ViewBag.Title = "Account";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="main">
    <h2>User Account</h2>
    <h4 class="text-success"> Welcome @Session["UName"] ... </h4>

    <p>
        <ul>

            <li>@Html.ActionLink("Upload New Art", "Upload", "SimpleArtGallery");</li>
            <li>@Html.ActionLink("Buy Art", "Index", "SimpleArtGallery");</li>

            <li>@Html.ActionLink("Upload To Auction Art", "Upload", "AuctionGallery");</li>
            <li>@Html.ActionLink("Start Bidding", "Index", "AuctionGallery");</li>

            <li>@Html.ActionLink("LogOut", "Logout", "Customer")</li>
        </ul>

        

    </p>
</div>


artgallery/Views/Customer/MemberLogin.cshtml
@model artgallery.Models.Member

@{
    ViewBag.Title = "MemberLogin";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>MemberLogin</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <h4>Member</h4>
    <h5 class="text-success"> @TempData["msg"]</h5>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })



    <div class="form-group">
        @Html.LabelFor(model => model.memberEmail, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.memberEmail, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.memberEmail, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.memberPassword, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.memberPassword, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.memberPassword, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">

        <p class="danger"> @ViewBag.error</p>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Login" class="btn btn-default" />

        </div>
    </div>

    @Html.ActionLink("Account", "Account",
     new { controller = "Customer" },
     new { @class = "btn btn-default" })

    @Html.ActionLink("Register Page", "Register",
     new { controller = "Customer" },
     new { @class = "btn btn-default" })

    @Html.ActionLink("Login As Admin", "LoginAdmin",
     new { controller = "AdministrativeCorner" },
     new { @class = "btn btn-default" })

</div>
}
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

artgallery/Views/Customer/Register.cshtml
@model artgallery.Models.Member
    

@{
    ViewBag.Title = "Register";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="main">
    <h2>Register</h2>


    @using (Html.BeginForm())   //Page, Model
    {
        @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>Member</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.memberFirstName, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.memberFirstName, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.memberFirstName, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.memberLastName, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.memberLastName, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.memberLastName, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.memberEmail, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.memberEmail, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.memberEmail, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.memberPassword, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.memberPassword, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.memberPassword, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.memberDOB, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.memberDOB, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.memberDOB, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.memberAddress, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.memberAddress, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.memberAddress, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.memberCity, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.memberCity, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.memberCity, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.memberZip, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.memberZip, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.memberZip, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.memberState, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.memberState, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.memberState, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.memberCountry, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.memberCountry, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.memberCountry, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.memberCellPhone, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.memberCellPhone, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.memberCellPhone, "", new { @class = "text-danger" })
        </div>
    </div>
     
    @*dateofjoining, memberapprovedAdmin, productsSold, productBuyed*@



    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Create" name="submit" class="btn btn-success" />

        </div>
    </div>
</div>
    }

<div>
  
    @Html.ActionLink("Login Page", "MemberLogin",
     new { controller = "Customer" },
     new { @class = "btn btn-default" })
</div>
    
    @section Scripts {
        @Scripts.Render("~/bundles/jqueryval")
    }
</div>